
application:
  name: strapi
  project: CHANGEME
  cpu: 800m
  ram: 512mb
  start_timeout: 480s
  publicly_accessible: true
  storage:
    - name: data
      type: ssd
      size: 5GB
      mount_point: /srv/app
databases:
- type: mysql
  version: 5.6
  name: my-sql
routers:
- name: main
  routes:
  - application_name: strapi
    paths:
    - /*
